FROM microsoft/nanoserver@sha256:8f78a4a7da4464973a5cd239732626141aec97e69ba3e4023357628630bc1ee2 as runtime
# This is a 1607 image which is available on the Appveyor agents
EXPOSE 80
EXPOSE 25

COPY Rnwood.Smtp4dev/docker /app

ENV ASPNETCORE_URLS=http://+:80 \
DOTNET_RUNNING_IN_CONTAINER=true

WORKDIR /app
ENTRYPOINT ["./Rnwood.Smtp4dev.exe"]